from pathlib import Path
path = Path('/home/ubuntu/pharmagarde_bf_expo/lib/pharmagarde/app-state.tsx')
text = path.read_text()
text = text.replace('import { sortPlacesByOpenThenDistance } from "./place-ordering";\nimport { AppPreferences, CombinedSearchItem, Coordinates, FavoriteItem, HealthPlace, Medicine, favoriteKey } from "./types";\n', 'import { sortPlacesByOpenThenDistance } from "./place-ordering";\nimport { fetchPremiumStatus, initPremiumPayment, limitFreeResults, type PaymentInitResponse, type PremiumPlanId } from "./premium";\nimport { AppPreferences, CombinedSearchItem, Coordinates, FavoriteItem, HealthPlace, Medicine, favoriteKey } from "./types";\n')
text = text.replace('  medicines: Medicine[];\n  favorites: FavoriteItem[];\n', '  medicines: Medicine[];\n  isPremium: boolean;\n  subscriptionEnd: string | null;\n  premiumLoading: boolean;\n  refreshPremiumStatus: () => Promise<void>;\n  initSubscription: (planId: PremiumPlanId) => Promise<PaymentInitResponse>;\n  favorites: FavoriteItem[];\n')
text = text.replace('  const [medicines, setMedicines] = useState<Medicine[]>(LOCAL_ESSENTIAL_MEDICINES);\n  const [favorites, setFavorites] = useState<FavoriteItem[]>([]);\n', '  const [medicines, setMedicines] = useState<Medicine[]>(LOCAL_ESSENTIAL_MEDICINES);\n  const [isPremium, setIsPremium] = useState(false);\n  const [subscriptionEnd, setSubscriptionEnd] = useState<string | null>(null);\n  const [premiumLoading, setPremiumLoading] = useState(false);\n  const [favorites, setFavorites] = useState<FavoriteItem[]>([]);\n')
insert_after = '  const isApiConfigured = apiBaseUrl.length > 0;\n\n'
refresh_block = '''  const refreshPremiumStatus = useCallback(async () => {\n    if (!isApiConfigured) {\n      setIsPremium(false);\n      setSubscriptionEnd(null);\n      return;\n    }\n\n    setPremiumLoading(true);\n    try {\n      const status = await fetchPremiumStatus();\n      setIsPremium(status.isPremium);\n      setSubscriptionEnd(status.subscriptionEnd);\n    } catch (error) {\n      console.warn("[PharmaGarde Premium] Impossible de récupérer le statut premium", error);\n      setIsPremium(false);\n      setSubscriptionEnd(null);\n    } finally {\n      setPremiumLoading(false);\n    }\n  }, [isApiConfigured]);\n\n  const initSubscription = useCallback(async (planId: PremiumPlanId) => {\n    const response = await initPremiumPayment(planId);\n    await refreshPremiumStatus().catch((error) => {\n      console.warn("[PharmaGarde Premium] Rafraîchissement du statut après paiement initialisé impossible", error);\n    });\n    return response;\n  }, [refreshPremiumStatus]);\n\n  useEffect(() => {\n    refreshPremiumStatus();\n  }, [refreshPremiumStatus]);\n\n'''
text = text.replace(insert_after, insert_after + refresh_block)
text = text.replace('      const nextPharmacies = sortPlacesByOpenThenDistance(withLocalDistances(filterPlacesByCity(pharmacyResult.value, activeCity), referenceLocation));\n      console.info("[PharmaGarde Frontend] Réponse pharmacies reçue", { selectedCity: activeCity, receivedCount: pharmacyResult.value.length, displayedCount: nextPharmacies.length, pharmacies: nextPharmacies });\n      setPharmacies(nextPharmacies);\n', '      const nextPharmacies = sortPlacesByOpenThenDistance(withLocalDistances(filterPlacesByCity(pharmacyResult.value, activeCity), referenceLocation));\n      const displayedPharmacies = limitFreeResults(nextPharmacies, isPremium);\n      console.info("[PharmaGarde Frontend] Réponse pharmacies reçue", { selectedCity: activeCity, receivedCount: pharmacyResult.value.length, displayedCount: displayedPharmacies.length, isPremium, pharmacies: displayedPharmacies });\n      setPharmacies(displayedPharmacies);\n')
text = text.replace('      const nextClinics = sortPlacesByOpenThenDistance(withLocalDistances(filterPlacesByCity(clinicResult.value, activeCity), referenceLocation));\n      console.info("[PharmaGarde Frontend] Réponse healthcare reçue", { selectedCity: activeCity, receivedCount: clinicResult.value.length, displayedCount: nextClinics.length });\n      setClinics(nextClinics);\n', '      const nextClinics = sortPlacesByOpenThenDistance(withLocalDistances(filterPlacesByCity(clinicResult.value, activeCity), referenceLocation));\n      const displayedClinics = limitFreeResults(nextClinics, isPremium);\n      console.info("[PharmaGarde Frontend] Réponse healthcare reçue", { selectedCity: activeCity, receivedCount: clinicResult.value.length, displayedCount: displayedClinics.length, isPremium });\n      setClinics(displayedClinics);\n')
text = text.replace('    if (medicineResult.status === "fulfilled" && medicineResult.value.length > 0) setMedicines(medicineResult.value);\n    else {\n      setMedicines(LOCAL_ESSENTIAL_MEDICINES);\n      nextErrors.medicines = medicineResult.status === "rejected" && medicineResult.reason instanceof Error ? `${medicineResult.reason.message} ${LOCAL_MEDICINES_NOTICE}` : LOCAL_MEDICINES_NOTICE;\n    }\n', '    if (!isPremium) {\n      setMedicines([]);\n    } else if (medicineResult.status === "fulfilled" && medicineResult.value.length > 0) setMedicines(medicineResult.value);\n    else {\n      setMedicines(LOCAL_ESSENTIAL_MEDICINES);\n      nextErrors.medicines = medicineResult.status === "rejected" && medicineResult.reason instanceof Error ? `${medicineResult.reason.message} ${LOCAL_MEDICINES_NOTICE}` : LOCAL_MEDICINES_NOTICE;\n    }\n')
text = text.replace('  }, [apiBaseUrl, isApiConfigured, isManualCitySelection, referenceLocation, selectedCity]);\n', '  }, [apiBaseUrl, isApiConfigured, isManualCitySelection, isPremium, referenceLocation, selectedCity]);\n')
text = text.replace('    medicines,\n    favorites,\n', '    medicines,\n    isPremium,\n    subscriptionEnd,\n    premiumLoading,\n    refreshPremiumStatus,\n    initSubscription,\n    favorites,\n')
text = text.replace('  }), [apiBaseUrl, clinics, errors, favoriteKeys, favorites, isApiConfigured, isManualCitySelection, loading, locationMessage, medicines, pharmacies, preferences, referenceLocation, refreshingLocation, requestLocation, refreshData, searchQuery, searchResults, selectedCity, selectCityManually, toggleFavorite, updateApiBaseUrl, updatePreference, userLocation]);\n', '  }), [apiBaseUrl, clinics, errors, favoriteKeys, favorites, initSubscription, isApiConfigured, isManualCitySelection, isPremium, loading, locationMessage, medicines, pharmacies, preferences, premiumLoading, referenceLocation, refreshData, refreshPremiumStatus, refreshingLocation, requestLocation, searchQuery, searchResults, selectedCity, selectCityManually, subscriptionEnd, toggleFavorite, updateApiBaseUrl, updatePreference, userLocation]);\n')
path.write_text(text)
